name: new-activitie-ci
on:
  push:
    branches:
      - 'feature/AEJ-DAYS**'
  workflow_dispatch:


jobs:
  call-reusable-workflow:
    uses: rg4amia/formation_day4/.github/workflows/ci_common.yaml@main
    with:
      sonar_host: "sonar-dev.agenceemploijeunes.ci"
      environment: dev
      channel_id: ${{ vars.CHANNEL_ID }}
      github_actor: ${{ github.actor }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

