name: new-activitie-ci
on:
  push:
    branches:
      - 'feature/AEJ-DAYS-4/**'
jobs:
  call-reusable-workflow:
    uses: rg4amia/formation_day4/.github/workflows/ci_common.yaml@main
    with:
      sonar_host: "sonar-dev.agenceemploijeunes.ci"
      environment: dev
      channel_id: ${{ vars.CHANNEL_ID }}
      job_status: ${{ job.status }}
      github_actor: ${{ github.actor }}
      runner_os: ${{ runner.os }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

