name: activitie-ci
on:
  push:
    branches:
      - 'feature/AEJ-4/**'
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          php: [7.4, 8.1, 8.2]
          os: [ubuntu-latest]
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          #php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Installer les dependences
        run: composer install --prefer-dist
      - name: Copy file .env.exemple to .env
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Execution des tests
        run: |
            echo "Execution des tests"
      - name: Post to a Slack channel
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ vars.CHANNEL_ID }}
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.actor }}\n${{ runner.os }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


