name: ci-three-jobs
on:
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
  #push:
    #branches:
      #- 'feature/**'
  workflow_display:
env:
  SONAR_DEV_URL: sonar-dev.egenceemploijeunes.ci
jobs:
  startbuild:
    runs-on: ubuntu-latest
    name: start-build
    steps:
        timeout-minutes: 1
        run: |
          echo "Start build..."
          sleep 1s
          echo "end build..."
          echo "status=done" >> "$GITHUB_OUTPUT"
    outputs:
      status: ${{ steps.start-build.outputs.status }}
  starttestprogr:
    needs: startbuild
    name: start-test-progr
    runs-on: ubuntu-latest
    steps:
      - if: ${{ steps.start-build.outputs.status == "done" }}
        run: |
          echo "start test non regression..."
          sleep 1s
          echo "end test non regression..."
          echo "testNonRegression=OK" >> "$GITHUB_OUTPUT"
    outputs:
      test-non-regression: ${{ steps.start-test-progr.testNonRegression }}
  sonalaunch:
    needs: starttestprogr
    name: sonar-launch
    runs-on: ubuntu-20.04
    steps:
      - if: ${{ steps.start-test-progr.outputs.test-non-regression == "OK" }}
        run: |
          echo $SONAR_DEV_URL
          echo ${{ RUNNER_OS }}
          sleep 2m
          echo "end Sonar Scanning"
      - name: message-slack
        if: ${{ cancel() }}
        run: |
              echo "Github a annulé mon job"

